Issue/16
roxannecvl/whokipedia pull request #23
Opened 2024-03-22 13:50 UTC by roxannecvl

This PR adds a list of about 100 celebrities. You can now from localhost:3000 select the name of a celebrity, a dropdown menu will suggest celebrities on the base of your current input and our listed celebrities. By pressing enter on your keyboard or by clicking on one of the celebrities of the menu it will automatically fetch and show you the data of the selected celebrity

2024-03-22 14:41 UTC, martinctl requested changes
Really good !
If you can try to create a separate page to test the search bar instead of adding it to `index.vue`, we are starting to get some conflicts by adding new functionalities on the same page.

2024-03-22 14:47 UTC, roxannecvl commented
@martinctl I can move it to another page if you want but for me in this case it goes with Jean's example and it complements it. Moreover, in this cas I've been careful not to have any merge conflicts with the main. For me it doesn't make sense to test this new functionality on its own, however I could, if you want move all index.vue to another page so as to keep the index.vue clean.

2024-03-22 15:06 UTC, JEANPRBT commented on model/CelebrityList.ts
> +
Remove those two lines, feels very empty at the beginning of the file.

2024-03-22 15:06 UTC, JEANPRBT commented on model/CelebrityList.ts
> + * and returns this name in its Wikipedia URL version
End comment with a dot and try to match each line's length in the documentation.

2024-03-22 15:06 UTC, JEANPRBT commented on model/CelebrityList.ts
> + * whose name is close to the query
Same as above. Also, maybe add a tiny explanation about Fuse.js since we don't all know what is it.

2024-03-22 15:06 UTC, JEANPRBT commented on pages/index.vue
> +import { getAutocompleteSuggestions} from "~/model/CelebrityList";
```suggestion
import { getAutocompleteSuggestions } from "~/model/CelebrityList";
```

2024-03-22 15:06 UTC, JEANPRBT commented on model/GameModel.ts
>  import {fetchIntro} from "~/api/wikipediaSource";
```suggestion
import { resolvePromise } from "./resolvePromise";
import { HintList, Hint } from "~/model/HintList";
import { Utils } from "~/utilities/Utils"
import { fetchIntro } from "~/api/wikipediaSource";
```

2024-03-22 15:12 UTC, martinctl commented
> @martinctl I can move it to another page if you want but for me in this case it goes with @JEANPRBT's example and it complements it. Moreover, in this cas I've been careful not to have any merge conflicts with the main. For me it doesn't make sense to test this new functionality on its own, however I could, if you want move all index.vue to another page so as to keep the index.vue clean.

I agree, it should have been moved before. You can move all `index.vue` then.

2024-03-22 15:58 UTC, martinctl approved these changes

2024-03-23 09:15 UTC, JEANPRBT approved these changes

2024-03-23 09:15 UTC, merged