Leaderboard V1
roxannecvl/whokipedia pull request #92
Opened 2024-04-11 07:24 UTC by MaelArrive

2024-04-11 11:56 UTC, martinctl requested changes

2024-04-11 11:56 UTC, martinctl commented on views/LeaderboardView.vue
By setting style to `text-black`, the font is hardly visible in dark mode. Please fix this

2024-04-16 09:13 UTC, roxannecvl commented
Also : 
- When I populate my stats and then go on the leaderboard I do not see myself, so I don't know how you get the data or if the current data is fake but it would be good to resolve that 
- Make the table scrollable without the headers being scrollable 
- Show the position of the current player better by highlighting it in a way

2024-04-18 09:01 UTC, roxannecvl approved these changes

2024-04-18 09:36 UTC, JEANPRBT approved these changes

2024-04-18 09:36 UTC, martinctl approved these changes

2024-04-18 09:38 UTC, merged